name: Release packages

env:
  CUSTOM_REG: ${{ secrets.CUSTOM_REG }}
  CUSTOM_AUTH_TOKEN: ${{ secrets.CUSTOM_AUTH_TOKEN }}
  NPMJS_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install
        run: yarn
      - name: Build
        run: |
          yarn build:core
      - name: Release @npmjs
        working-directory: packages/core
        run: |
          cat > .npmrc <<EOF
          //registry.npmjs.org/:_authToken=$NPMJS_AUTH_TOKEN
          EOF
          yarn publish --non-interactive --access public
          rm .npmrc
      - name: Release @artifactory
        working-directory: packages/core
        run: |
          cat > .npmrc <<EOF
          //$CUSTOM_REG/:_authToken=$CUSTOM_AUTH_TOKEN
          EOF
          yarn publish --non-interactive --access public
          rm .npmrc
